// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace FilenameBuilder
{
	public partial class counterTxtBox : NSViewController
	{
		public counterTxtBox (IntPtr handle) : base (handle)
		{
		}
	}
}
