// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace FilenameBuilder
{
	public partial class FireworksViewController : NSViewController
	{
		public FireworksViewController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
        }
    }
}
